# Generated by Django 2.2.3 on 2023-06-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('constituency_type', models.CharField(choices=[('parliamentary', 'Parliamentary'), ('assembly', 'Assembly')], max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='parliamentary',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='parliamentary',
        ),
        migrations.AlterField(
            model_name='candidates',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EC_Admin.Constituency'),
        ),
        migrations.AddField(
            model_name='voters',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EC_Admin.Constituency'),
        ),
    ]
